### ISSUE TITLE
mac killed: 9

### ISSUE THREAD

**Issue by rc452860** [hteen/docker-ngrok#3]
![image](https://user-images.githubusercontent.com/3949222/28399175-080ac160-6d3e-11e7-9a55-46e598ed5d6d.png)

**Comment by hteen** [comment]
@rc452860  https://hteen.cn/docker/docker-ngrok.html

**Comment by rc452860** [comment]
@hteen 看过了。不知道为啥莫名其妙的又好了。这个docker有点问题我自己又写了一个编译的linux版本只有一个而且不是arm64的 linux上执行报错。
